Feature/tcp server module
UCSB-CS189-2016-17-Aerospace/Aerocube pull request #4
Opened 2016-11-20 18:24 UTC by Gustavo-Cornejo

Added the tcp server module, including tests for it. I had a hard time setting up the server to client communication within the same file in the tests. I ended up just setting up a different file mockClient.py that should be ran with testTCPserver.py. Feel free to message me for any questions/doubts. Gracias.

2016-11-20 21:20 UTC, andrewtran1995 requested changes
Just some changes to improve the clarity of what the code is doing.

2016-11-20 21:20 UTC, andrewtran1995 commented on controller/testTCPserver.py
> +from tcpServer import *
Since it seems like you're only importing TcpServer, I'd just make that explicit to give the code more clarity.

2016-11-20 21:20 UTC, andrewtran1995 commented on controller/testingClass.py
> +class TestClass:
I'd want to rename this file and the class to be more specific to what you're testing.

2016-11-20 21:20 UTC, andrewtran1995 commented on controller/testTCPserver.py
> +	# sometimes gives resourcewarning: unclosed socket, but tearDown func does call close_connection()
Thanks for the documentation!

2016-11-20 21:20 UTC, andrewtran1995 commented on controller/testTCPserver.py
> +# in order to run tests, run this file and then run mockClient.py
Could make a README.md for this folder and put these details in there (e.g., under a section called "Usage").

2016-11-20 21:23 UTC, GusAlejandro commented on controller/testingClass.py
> +class TestClass:
okay, I'll rename the one in the TCP client as well

2016-11-22 07:43 UTC, andrewtran1995 approved these changes

2016-11-22 07:44 UTC, merged