Feature/design controller
UCSB-CS189-2016-17-Aerospace/Aerocube pull request #9
Opened 2016-12-04 02:28 UTC by andrewtran1995

**NOTE**: Developed primarily on the Jetson with pair programming, due to the many dependences needed (many of which are installed on the Jetson and readily available).
## Major Changes
* **EventHandler**
   * Complete overhaul of behavior and implementation
   * Behavior defined and influenced by states (4 possible states total)
* **AeroCubeEvent**
   * Ability to encode AeroCubeEvent objects as stringified JSON objects
   * Ability to decode ("rehydrate") AeroCubeEvent objects from JSON objects
* **Controller**
   * All of controller implemented
   * Listens to incoming messages via TCP Server and calls methods depending on signal
* **TcpService**
   * TCP client and server code moved to its own Python module
   * TcpUtil class provides functionality to encode/decode messages for TCP transmission
## Known Issues
* Tests
* Documentation

2016-12-06 08:04 UTC, andrewtran1995 commented on clearPort5005.sh
> +sudo fuser -k 5005/tcp
Should be moved into general-purpose "scripts" folder (along with potentially all other *.sh files currently in the top-level directory right now).

2016-12-06 08:04 UTC, andrewtran1995 commented on controller/controller.py
> +        self.server = TcpServer('127.0.0.1', 5005, 1024)
Params (especially IP and port) could be moved into settings file.

2016-12-06 08:04 UTC, andrewtran1995 commented on controller/controller.py
> +        print('Controller.return_status: Status is {}'.format(status))
Print statements should be handled by a logger.

2016-12-06 08:04 UTC, andrewtran1995 commented on controller/controller.py
> +    def draw_and_store_image_with_detected_markers(self, database, scan_id, img_path, output_path, scan_results):
Method created for class demo, and should either be refactored or removed.

2016-12-06 08:04 UTC, andrewtran1995 commented on controller/testController.py
> +class TestController(unittest.TestCase):
Need unit tests for the controller.

Need integration tests for controller and event handler interaction.

2016-12-06 08:04 UTC, andrewtran1995 commented on dataStorage/dataStorage.py
> +def store_image(location, img):
Needs unit tests, documentation, and perhaps some refactoring? For example, does not check if image already exists or if valid img path.

2016-12-06 08:04 UTC, andrewtran1995 commented on eventClass/aeroCubeEvent.py
> +        if class_name == ImageEvent.__name__:
Should try to refactor this method to make it more scalable / less brittle. Need to somehow resolve the issue of constructing different types of AeroCubeEvents which may require different arguments in their constructors. Perhaps each class should have a static method that "rehydrates from JSON"?

2016-12-06 08:04 UTC, andrewtran1995 commented on eventClass/aeroCubeSignal.py
> +    def __str__(self):
Perhaps the __str__ behavior could be abstracted somehow -- could be possible if AeroCubeSignal inherits from Enum and everything else inherits from it? Unsure how this behavior could effect Enum behavior.

2016-12-06 08:04 UTC, andrewtran1995 commented on eventClass/aeroCubeSignal.py
> +class ResultEventSignal(Enum):
Need way to signify if a result event is final or not. Could be done with a subclass or a method.

2016-12-06 08:04 UTC, andrewtran1995 commented on eventClass/eventHandler.py
>  class EventHandler(object):
Class definitely needs more documentation to clarify its behavior (in terms of the different states and how state transitions should occur, both publicly and internally).

2016-12-06 08:04 UTC, andrewtran1995 commented on externalComm/externalComm.py
>  def process(func, database, scanID, location=None, data=None, testing=False):
Could be refactored so that calls from the controller can be more clear.

2016-12-06 08:04 UTC, andrewtran1995 commented on flaskServer/mockTcpEventHandler.py
> +	client = TcpClient('127.0.0.1',5005,1024)
IP and port arguments shoudl be moved to settings file.

2016-12-06 08:04 UTC, andrewtran1995 commented on flaskServer/restEndpoint.py
> +client = TcpClient('127.0.0.1', 5005, 1024)
IP and port should be moved to settings file.

2016-12-06 08:04 UTC, andrewtran1995 commented on flaskServer/restEndpoint.py
> +app.config['UPLOAD_FOLDER'] = 'flaskServer/static/img/'
In order to make the repository cloneable on the Jetson without much issue, perhaps we should try to stick to relative file paths. If so, we should sweep through all of the files (including ImP files) to make the appropriate changes. Something cool could be setting a "root" or "home" directory at the top-level directory of the repo that all Python packages have access to.

2016-12-08 22:44 UTC, andrewtran1995 commented
@elswenson, would it be appropriate to merge this branch or no?

2016-12-10 07:39 UTC, elswenson requested changes
I would rather not merge this until at least some of the problems that have been outlined have been addressed. I'll take a look at this over this weekend to see what can be cleaned up relatively easily.

2016-12-10 07:39 UTC, elswenson commented on controller/controller.py
> +    def draw_and_store_image_with_detected_markers(self, database, scan_id, img_path, output_path, scan_results):
Removed seems to be the best choice

2016-12-10 07:39 UTC, elswenson commented on eventClass/aeroCubeEvent.py
> +
Should define a to_json function that returns the object in json representation. __str__ Should not be used for this.

2016-12-10 07:39 UTC, elswenson commented on eventClass/aeroCubeEvent.py
> +        if class_name == ImageEvent.__name__:
A good start would be to look into better ways of determining the class that the JSON represents, that's where many of the problems lie.

2016-12-10 07:39 UTC, elswenson commented on eventClass/aeroCubeSignal.py
> +class ResultEventSignal(Enum):
I'm in favor of a subclass

2016-12-10 07:39 UTC, elswenson commented on eventClass/bundle.py
> +    def __str__(self):
Once again this should be moved to a to_json method, the __str__ method should not be used to create a JSON representation.

2016-12-10 07:39 UTC, elswenson commented on eventClass/eventHandler.py
>  class EventHandler(object):
Within the file itself, the functions should be re-ordered, the current order/groupings aren't very coherent.

2016-12-10 07:39 UTC, elswenson commented on externalComm/commClass.py
> +    def __init__(self, testing=False):
The API config should be moved to a separate settings file

2016-12-10 07:39 UTC, elswenson commented on externalComm/commClass.py
>  class FirebaseComm(Comm):
Need to add logging to this class.

2016-12-10 07:39 UTC, elswenson commented on externalComm/commClass.py
>  class FirebaseComm(Comm):
We should also look at refactoring the functions in this class into protected/public parts.

2016-12-10 07:39 UTC, elswenson commented on externalComm/commClass.py
>          user = auth.sign_in_with_email_and_password('yourfirenation@gmail.com', 'yourfirenation')
Need to check for potential errors in this flow

2016-12-10 07:39 UTC, elswenson commented on flaskServer/requirements.txt
> +dill==0.2.5
dill should be removed, we are no longer using it.

2016-12-10 07:39 UTC, elswenson commented on flaskServer/restEndpoint.py
> +CORS(app)
Need to look into handling CORS problems when using a locally hosted web application in a browser to access a local socket process

2016-12-10 07:39 UTC, elswenson commented on tcpService/tcpUtils.py
> +class TcpUtil(object):
We should look for other encoding methods

2016-12-10 07:39 UTC, elswenson commented on dataStorage/dataStorage.py
>          pickle.dump(json, open(location, "wb"), pickle.HIGHEST_PROTOCOL)
Pickle is not a valid long-term solution for long-term storage, plus reliance on the structure of the classes could cause development problems if the stored files are not cleared when potentially breaking changes are made to class structures.

2016-12-14 10:58 UTC, andrewtran1995 commented
@elswenson, do you know what other specific changes you would want to see before we merge?

2016-12-15 16:19 UTC, elswenson commented
@andrewtran1995 I'll check again today. I'm not entirely sure.

2016-12-24 20:22 UTC, merged